name: Scala CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Set up Fuseki
        run: docker run --rm -d -p 3030:3030 -v $(pwd):/usr/share/data atomgraph/fuseki  --file /usr/share/data/src/test/resources/ehri-skos.ttl /example
      - name: Run tests
        run: sbt test
